-------------------------- LANÇAMENTO CONTABEIS
CREATE TABLE CONTA(
	CONTA_ID BIGINT NOT NULL IDENTITY(1,1),
	CONTA_PLANO VARCHAR(20),
	CONTA VARCHAR(50),
	CONTA_SUP BIGINT,
	PATRIMONIO_RESULT VARCHAR(2),
	ATIVO_PASSIVO VARCHAR(2)
    CONSTRAINT PK_ESTADO PRIMARY KEY (CONTA_ID),
	CONSTRAINT FK_CONTA_CONTASUP FOREIGN KEY (CONTA_SUP)
        REFERENCES CONTA (CONTA_ID)
);

CREATE TABLE HISTORICO(
	HISTORICO_ID BIGINT NOT NULL IDENTITY(1,1),
	HISTORICO VARCHAR(100)
    CONSTRAINT PK_HISTORICO PRIMARY KEY (HISTORICO_ID)	
); 

CREATE TABLE TP_OPERACAO(
	TP_OPERACAO_ID BIGINT NOT NULL IDENTITY(1,1),
	TP_OPERACAO VARCHAR(50),
	HISTORICO_ID BIGINT,
    CONSTRAINT PK_TP_OPERACAO PRIMARY KEY (TP_OPERACAO_ID),
	CONSTRAINT FK_TP_OPERACAO_HISTORICO FOREIGN KEY (HISTORICO_ID)
        REFERENCES HISTORICO (HISTORICO_ID),
); 

CREATE TABLE LCTO_CONTABIL(
	LCTO_ID BIGINT NOT NULL IDENTITY(1,1),
	HISTORICO_ID BIGINT,
	DATA DATE,
	COMPLEMENTO VARCHAR (100),
    CONSTRAINT PK_LCTO PRIMARY KEY (LCTO_ID),
	CONSTRAINT FK_LCTO_HISTORICO FOREIGN KEY (HISTORICO_ID)
        REFERENCES HISTORICO (HISTORICO_ID)
);

CREATE TABLE LCTO_DEBITO(
	LCTO_DEB_ID BIGINT NOT NULL IDENTITY(1,1),
	LCTO_ID BIGINT NOT NULL,
	CONTA_ID BIGINT NOT NULL,
	VALOR NUMERIC(15,2),
	CONSTRAINT PK_LCTO_DEB PRIMARY KEY (LCTO_DEB_ID),
	CONSTRAINT FK_LCTO_DEB_LCTO FOREIGN KEY (LCTO_ID)
        REFERENCES LCTO_CONTABIL (LCTO_ID),
	CONSTRAINT FK_LCTO_DEB_CONTA FOREIGN KEY (CONTA_ID)
        REFERENCES CONTA (CONTA_ID)
);

CREATE TABLE LCTO_CREDITO(
	LCTO_CRED_ID BIGINT NOT NULL IDENTITY(1,1),
	LCTO_ID BIGINT NOT NULL,
	CONTA_ID BIGINT NOT NULL,
	VALOR NUMERIC(15,2),
	CONSTRAINT PK_LCTO_CRED PRIMARY KEY (LCTO_CRED_ID),
	CONSTRAINT FK_LCTO_CRED_LCTO FOREIGN KEY (LCTO_ID)
        REFERENCES LCTO_CONTABIL (LCTO_ID),
	CONSTRAINT FK_LCTO_CRED_CONTA FOREIGN KEY (CONTA_ID)
        REFERENCES CONTA (CONTA_ID)
);

CREATE TABLE PARAMETRO(
	PARAM_ID BIGINT NOT NULL IDENTITY(1,1),
	CONTA_ID BIGINT NOT NULL,
	TP_OPERACAO_ID BIGINT NOT NULL,
	TIPO CHAR(2),
	CONSTRAINT PK_PARAMETRO PRIMARY KEY (PARAM_ID),	
	CONSTRAINT FK_PARAM_TP_OPERACAO FOREIGN KEY (TP_OPERACAO_ID)
        REFERENCES TP_OPERACAO (TP_OPERACAO_ID),
	CONSTRAINT FK_PARAM_CONTA FOREIGN KEY (CONTA_ID)
        REFERENCES CONTA (CONTA_ID)
);

-------------------------- ESTOQUE

CREATE TABLE UNIDADE_MEDIDA (
  id_unidade INT NOT NULL IDENTITY(1,1),
  titulo_unidade VARCHAR(50) NULL,
  DESCRICAO_UNIDADE VARCHAR(500) NULL,
  PRIMARY KEY (id_unidade));


-- -----------------------------------------------------
-- Table PRATELEIRA
-- -----------------------------------------------------
CREATE TABLE PRATELEIRA (
  id_prateleira INT NOT NULL IDENTITY(1,1),
  titulo_prateleira VARCHAR(50) NULL,
  descricao_prateleira VARCHAR(500) NULL,
  id_unidade INT NOT NULL,
  PRIMARY KEY (id_prateleira),
  INDEX fk_PRATELEIRA_UNIDADE_MEDIDA1_idx (id_unidade ASC),
  CONSTRAINT fk_PRATELEIRA_UNIDADE_MEDIDA1
    FOREIGN KEY (id_unidade)
    REFERENCES UNIDADE_MEDIDA (id_unidade)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table PRODUTO
-- -----------------------------------------------------
CREATE TABLE PRODUTO (
  id_produto INT NOT NULL IDENTITY(1,1),
  nome_produto VARCHAR(50) NULL,
  descricao_produto VARCHAR(500) NULL,
  qtde INT NULL,
  id_unidade INT NOT NULL,
  id_prateleira INT NOT NULL,
  PRIMARY KEY (id_produto),
  INDEX fk_PRODUTO_UNIDADE_MEDIDA_idx (id_unidade ASC),
  INDEX fk_PRODUTO_PRATELEIRA1_idx (id_prateleira ASC),
  CONSTRAINT fk_PRODUTO_UNIDADE_MEDIDA
    FOREIGN KEY (id_unidade)
    REFERENCES UNIDADE_MEDIDA (id_unidade)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PRODUTO_PRATELEIRA1
    FOREIGN KEY (id_prateleira)
    REFERENCES PRATELEIRA (id_prateleira)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table DOCUMENTO
-- -----------------------------------------------------
CREATE TABLE DOCUMENTO (
  id_documento INT NOT NULL IDENTITY(1,1),
  valor DECIMAL(15,2) NULL,
  serie VARCHAR(100) NULL,
  lote VARCHAR(100) NULL,
  data DATETIME NULL,
  cod INT NOT NULL,
  tp_operacao_id INT NULL,
  tp_pagamento INT NULL,
  PRIMARY KEY (id_documento));


-- -----------------------------------------------------
-- Table ITEM_DOCUMENTO
-- -----------------------------------------------------
CREATE TABLE ITEM_DOCUMENTO (
  id_item_doc INT NOT NULL IDENTITY(1,1),
  qtde INT NULL,
  valor_unitario DECIMAL(15,2) NULL,
  id_produto INT NOT NULL,
  id_documento INT NOT NULL,
  PRIMARY KEY (id_item_doc),
  INDEX fk_ITEM_DOCUMENTO_PRODUTO1_idx (id_produto ASC),
  INDEX fk_ITEM_DOCUMENTO_DOCUMENTO1_idx (id_documento ASC),
  CONSTRAINT fk_ITEM_DOCUMENTO_PRODUTO1
    FOREIGN KEY (id_produto)
    REFERENCES PRODUTO (id_produto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ITEM_DOCUMENTO_DOCUMENTO1
    FOREIGN KEY (id_documento)
    REFERENCES DOCUMENTO (id_documento)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table SALDO_ESTOQUE
-- -----------------------------------------------------
CREATE TABLE SALDO_ESTOQUE (
  id_saldo_estoque INT NOT NULL IDENTITY(1,1),
  data_movimentacao DATETIME NULL,
  qtde INT NULL,
  id_unidade INT NOT NULL,
  id_prateleira INT NOT NULL,
  PRIMARY KEY (id_saldo_estoque),
  INDEX fk_SALDO_ESTOQUE_UNIDADE_MEDIDA1_idx (id_unidade ASC),
  INDEX fk_SALDO_ESTOQUE_PRATELEIRA1_idx (id_prateleira ASC),
  CONSTRAINT fk_SALDO_ESTOQUE_UNIDADE_MEDIDA1
    FOREIGN KEY (id_unidade)
    REFERENCES UNIDADE_MEDIDA (id_unidade)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_SALDO_ESTOQUE_PRATELEIRA1
    FOREIGN KEY (id_prateleira)
    REFERENCES PRATELEIRA (id_prateleira)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


----- CONTAS A RECEBER/PAGAR

CREATE TABLE [DBO].[CLIENTEFORNECEDOR](
	[COD] [INT] NOT NULL,
	[TIPO] [VARCHAR](20) NOT NULL,
	[CPF_CNPJ] [INT] NOT NULL,
	[RG_IE] [INT] NOT NULL,
	[NOME_RAZAO] [VARCHAR](200) NOT NULL,
	[CEP] [VARCHAR](20) NOT NULL,
	[ENDERECO] [VARCHAR](50) NOT NULL,
	[NUMERO] [VARCHAR](20) NOT NULL,
	[CIDADE] [VARCHAR](50) NOT NULL,
	[BAIRRO] [VARCHAR](50) NOT NULL,
	[COMPLEMENTO] [VARCHAR](50) NOT NULL,
	[UF] [VARCHAR](2) NOT NULL,
	[PAIS] [VARCHAR](50) NOT NULL,
	[TELEFONEPRINCIPAL] [VARCHAR](50) NOT NULL,
	[TELEFONESECUNDARIO] [VARCHAR](50) NOT NULL,
	[EMAIL] [VARCHAR](50) NOT NULL,
 CONSTRAINT [PK_CLIENTEFORNECEDORE] PRIMARY KEY CLUSTERED 
(
	[COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [DBO].[LANCAMENTOSTITULOS](
	[ID] [INT] NOT NULL,
	[TIPOOPERACAO] [VARCHAR](50) NOT NULL,
	[COD_CLIENTEFORNECEDOR] [INT] NOT NULL,
	[COD_CONTADEB] [INT] NOT NULL,
	[COD_CONTACRED] [INT] NOT NULL,
	[NUMDOCUMENTO] [VARCHAR](50) NOT NULL,
	[DATALANCAMENTO] [DATE] NOT NULL,
	[DATAVENCIMENTO] [DATE] NOT NULL,
	[DATAPAGAMENTO] [DATE] NOT NULL,
	[FORMAPAGAMENTO] [VARCHAR](50) NOT NULL,
	[NUMPARCELAS] [INT] NOT NULL,
	[VALORDOCUMENTO] [INT] NOT NULL,
	[COD_TIPODOCUMENTO] [INT] NOT NULL,
	[COD_HISTORICO] [BIGINT] NOT NULL,
 CONSTRAINT [PK_TITULOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [DBO].[LANCAMENTOSTITULOS]  WITH CHECK ADD  CONSTRAINT [FK_LANCAMENTOSTITULOS_CLIENTEFORNECEDOR] FOREIGN KEY([COD_CLIENTEFORNECEDOR])
REFERENCES [DBO].[CLIENTEFORNECEDOR] ([COD])


ALTER TABLE [DBO].[LANCAMENTOSTITULOS] CHECK CONSTRAINT [FK_LANCAMENTOSTITULOS_CLIENTEFORNECEDOR]


ALTER TABLE [DBO].[LANCAMENTOSTITULOS]  WITH CHECK ADD  CONSTRAINT [FK_LANCAMENTOSTITULOS_HISTORICO] FOREIGN KEY([COD_HISTORICO])
REFERENCES [DBO].[HISTORICO] ([HISTORICO_ID])


ALTER TABLE [DBO].[LANCAMENTOSTITULOS] CHECK CONSTRAINT [FK_LANCAMENTOSTITULOS_HISTORICO]

------

